name: MacOS Virtual Machine
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    name: MacOS Build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setting Up the MacOS Environment
      env:
        TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
        MAC_USER_PASSWORD: ${{ secrets.MAC_USER_PASSWORD }}
        VNC_PASSWORD: ${{ secrets.VNC_PASSWORD }}
        MAC_REALNAME: ${{ secrets.MAC_REALNAME }}
        MAC_HOSTNAME: ${{ secrets.MAC_HOSTNAME }}
      run: source macos-run.sh "$MAC_USER_PASSWORD" "$VNC_PASSWORD" "$TAILSCALE_AUTH_KEY" "$MAC_REALNAME" "$MAC_HOSTNAME"
    - name: Show Tailscale IP for VNC Connection
      run: tailscale ip -4
    - name: Keep Running MacOS System and keepAlive
      uses: mxschmitt/action-tmate@v2
